version: 0.2

phases:
  install: 
    commands:
      - echo Starting build
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ${REGION})
      - chmod +x dev-ops/*.sh
  build:
    commands:
      - echo Build started on `date`
      - cd add-sub && ../dev-ops/build-docker-image.sh  express-add-sub  ${ECR_URL} && cd ..
      - cd mult-div && ../dev-ops/build-docker-image.sh  express-mult-div  ${ECR_URL} && cd ..
      - cd rest-arith && ../dev-ops/build-docker-image.sh  express-rest-rith  ${ECR_URL} && cd ..
      - pwd
  post_build:
    commands:
      - echo pushing images now
      - ./dev-ops/push-docker-image.sh express-add-sub  ${ECR_URL}
      - ./dev-ops/push-docker-image.sh express-mult-div  ${ECR_URL}
      - ./dev-ops/push-docker-image.sh express-rest-rith  ${ECR_URL}
  artifacts:
    files:
      - express-add-sub.json
      - express-mult-div.json
      - express-rest-rith.json

